service:
  name: serverless-leaderboard-api

plugins:
  - serverless-webpack
  - serverless-prune-plugin
  - serverless-offline

custom:
  updateActorFunctionName: ${self:service.name}-${self:provider.stage}-updateActor
  webpack:
    includeModules:
      forceExclude:
        - aws-sdk
        - better-sqlite3
  prune:
    automatic: true
    number: 7

package:
  excludeDevDependencies: true
  individually: true

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-2
  tracing:
    apiGateway: true
    lambda: true
  apiGateway:
    minimumCompressionSize: 1024
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource:
        - Fn::Join:
            - ":"
            - - "arn:aws:lambda"
              - Ref: "AWS::Region"
              - Ref: "AWS::AccountId"
              - "function"
              - ${self:custom.updateActorFunctionName}
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    REDIS_HOST: ${env:REDIS_HOST}
    REDIS_PASSWORD: ${env:REDIS_PASSWORD}
    ADMIN_SECRET: ${env:ADMIN_SECRET}
    UPDATE_ACTOR_FUNCTION_NAME: ${self:custom.updateActorFunctionName}

functions:
  update:
    handler: src/handlers/update/handler.handle
    timeout: 10
    layers:
      - arn:aws:lambda:ap-northeast-2:467731270623:layer:BetterSqlite3:4
    events:
      - http: PUT /{serviceId}/{period}
  updateActor:
    handler: src/handlers/updateActor/handler.handle
    timeout: 180
    layers:
      - arn:aws:lambda:ap-northeast-2:467731270623:layer:BetterSqlite3:4
  getAll:
    handler: src/handlers/getAll.handle
    layers:
      - arn:aws:lambda:ap-northeast-2:467731270623:layer:BetterSqlite3:4
    events:
      - http: GET /{serviceId}/{period}
  top:
    handler: src/handlers/top.handle
    layers:
      - arn:aws:lambda:ap-northeast-2:467731270623:layer:BetterSqlite3:4
    events:
      - http: GET /{serviceId}/{period}/top
  me:
    handler: src/handlers/me.handle
    layers:
      - arn:aws:lambda:ap-northeast-2:467731270623:layer:BetterSqlite3:4
    events:
      - http: GET /{serviceId}/{period}/me
  around:
    handler: src/handlers/around.handle
    layers:
      - arn:aws:lambda:ap-northeast-2:467731270623:layer:BetterSqlite3:4
    events:
      - http: GET /{serviceId}/{period}/around
  drop:
    handler: src/handlers/drop.handle
    layers:
      - arn:aws:lambda:ap-northeast-2:467731270623:layer:BetterSqlite3:4
    events:
      - http: DELETE /{serviceId}/{period}
